import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>QR Code
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div id="base">
          <img id="image" src="/image-qr-code.png"></img>
          <p id="first">Improve your front-end skills by building projects</p>
          <p id="second">Scan the QR code to visit Frontend Mentor and take your coding skills to the next level</p>
        </div>
      </main>

      <footer >

      </footer>
    </div>
  )
}
